'use client';

/**
 * ReportPreview Component
 *
 * Displays a preview of generated report data with export options.
 *
 * @module components/domain/reports/ReportPreview
 */

import React, { useCallback, useState } from 'react';

import {
  FileTextOutlined,
  FilePdfOutlined,
  FileExcelOutlined,
  DownloadOutlined,
  PrinterOutlined,
  LoadingOutlined,
} from '@ant-design/icons';
import { Card, Table, Typography, Space, Statistic, Dropdown, message } from 'antd';
import { useTranslations } from 'next-intl';

import { EmptyState } from '@/components/common/data/EmptyState';
import { Button } from '@/components/ui/Button';
import { cn } from '@/lib/utils/cn';
import { exportToPDF, exportToExcel, exportToJSON, type ExportData } from '@/lib/utils/export';

import type { ColumnsType } from 'antd/es/table';

const { Title, Text } = Typography;

// =============================================================================
// TYPES
// =============================================================================

export interface ReportColumn {
  key: string;
  title: string;
  width?: number;
  render?: (value: unknown, record: Record<string, unknown>) => React.ReactNode;
}

export interface ReportPreviewProps {
  /** Report title */
  title: string;
  /** Optional subtitle for the report */
  subtitle?: string;
  /** Column definitions for the report table */
  columns: ReportColumn[];
  /** Report data records */
  data: Record<string, unknown>[];
  /** Summary statistics to display above the table */
  summary?: Record<string, string | number>;
  /** Whether the report is loading */
  loading?: boolean;
  /** Error message if report generation failed */
  error?: string | null;
  /** Additional CSS class name */
  className?: string;
}

// =============================================================================
// COMPONENT
// =============================================================================

/**
 * ReportPreview Component
 *
 * A comprehensive report preview component that displays:
 * - Report header with title and subtitle
 * - Export buttons (PDF, Excel, JSON) and print functionality
 * - Summary statistics section
 * - Data table with pagination
 * - Loading, empty, and error states
 */
export function ReportPreview({
  title,
  subtitle,
  columns,
  data,
  summary,
  loading = false,
  error = null,
  className,
}: ReportPreviewProps): React.JSX.Element {
  const t = useTranslations('reports.preview');
  const [exporting, setExporting] = useState<'pdf' | 'excel' | 'json' | null>(null);

  // ===========================================================================
  // EXPORT HELPERS
  // ===========================================================================

  /**
   * Prepare export data structure
   */
  const getExportData = useCallback(
    (): ExportData => ({
      title,
      subtitle,
      columns: columns.map((col) => ({
        key: col.key,
        title: col.title,
        width: col.width,
      })),
      data,
      summary,
      footer: `Generated by Aymur Platform - ${new Date().toLocaleString()}`,
    }),
    [title, subtitle, columns, data, summary]
  );

  // ===========================================================================
  // HANDLERS
  // ===========================================================================

  const handleExportPDF = useCallback(async () => {
    setExporting('pdf');
    try {
      await exportToPDF(getExportData());
      message.success(t('exportSuccess', { format: 'PDF' }));
    } catch {
      message.error(t('exportError', { format: 'PDF' }));
    } finally {
      setExporting(null);
    }
  }, [getExportData, t]);

  const handleExportExcel = useCallback(async () => {
    setExporting('excel');
    try {
      await exportToExcel(getExportData());
      message.success(t('exportSuccess', { format: 'Excel' }));
    } catch {
      message.error(t('exportError', { format: 'Excel' }));
    } finally {
      setExporting(null);
    }
  }, [getExportData, t]);

  const handleExportJSON = useCallback(() => {
    setExporting('json');
    try {
      exportToJSON(getExportData());
      message.success(t('exportSuccess', { format: 'JSON' }));
    } catch {
      message.error(t('exportError', { format: 'JSON' }));
    } finally {
      setExporting(null);
    }
  }, [getExportData, t]);

  const handlePrint = useCallback(() => {
    window.print();
  }, []);

  // ===========================================================================
  // TABLE CONFIGURATION
  // ===========================================================================

  const tableColumns: ColumnsType<Record<string, unknown>> = columns.map((col) => ({
    title: col.title,
    dataIndex: col.key,
    key: col.key,
    width: col.width,
    render: col.render,
  }));

  // ===========================================================================
  // EXPORT MENU
  // ===========================================================================

  const exportMenuItems = [
    {
      key: 'pdf',
      label: t('exportPDF'),
      icon: <FilePdfOutlined />,
      onClick: handleExportPDF,
    },
    {
      key: 'excel',
      label: t('exportExcel'),
      icon: <FileExcelOutlined />,
      onClick: handleExportExcel,
    },
    {
      key: 'json',
      label: t('exportJSON'),
      icon: <FileTextOutlined />,
      onClick: handleExportJSON,
    },
  ];

  // ===========================================================================
  // RENDER: ERROR STATE
  // ===========================================================================

  if (error) {
    return (
      <Card className={cn('border border-red-200', className)}>
        <EmptyState icon={<FileTextOutlined />} title={t('errorTitle')} description={error} />
      </Card>
    );
  }

  // ===========================================================================
  // RENDER: EMPTY STATE
  // ===========================================================================

  if (!loading && data.length === 0) {
    return (
      <Card className={cn('border border-stone-200', className)}>
        <EmptyState
          icon={<FileTextOutlined />}
          title={t('emptyTitle')}
          description={t('emptyDescription')}
        />
      </Card>
    );
  }

  // ===========================================================================
  // RENDER: MAIN CONTENT
  // ===========================================================================

  return (
    <Card
      className={cn('border border-stone-200 print:border-0 print:shadow-none', className)}
      styles={{ body: { padding: 0 } }}
    >
      {/* Header Section */}
      <div className="flex items-center justify-between px-6 py-4 border-b border-stone-100 print:border-b-2 print:border-amber-500">
        <div>
          <Title level={4} className="m-0 text-stone-900">
            {title}
          </Title>
          {subtitle && (
            <Text type="secondary" className="text-sm">
              {subtitle}
            </Text>
          )}
        </div>

        {/* Export and Print Actions */}
        <Space className="print:hidden">
          <Dropdown menu={{ items: exportMenuItems }} trigger={['click']}>
            <Button
              icon={exporting ? <LoadingOutlined /> : <DownloadOutlined />}
              loading={!!exporting}
            >
              {t('export')}
            </Button>
          </Dropdown>
          <Button icon={<PrinterOutlined />} onClick={handlePrint}>
            {t('print')}
          </Button>
        </Space>
      </div>

      {/* Summary Section */}
      {summary && Object.keys(summary).length > 0 && (
        <div className="px-6 py-4 bg-amber-50 border-b border-amber-100">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {Object.entries(summary).map(([key, value]) => (
              <Statistic
                key={key}
                title={
                  <span className="text-stone-600">
                    {key.replace(/_/g, ' ').replace(/\b\w/g, (l) => l.toUpperCase())}
                  </span>
                }
                value={value}
                valueStyle={{ color: '#92400e', fontWeight: 600 }}
              />
            ))}
          </div>
        </div>
      )}

      {/* Data Table */}
      <div className="p-6">
        <Table
          dataSource={data}
          columns={tableColumns}
          loading={loading}
          rowKey={(record, index) => String(record.id ?? index)}
          pagination={{
            pageSize: 20,
            showSizeChanger: true,
            showTotal: (total) => t('totalRows', { count: total }),
          }}
          scroll={{ x: 'max-content' }}
          size="small"
          className={cn(
            '[&_.ant-table-thead_th]:bg-stone-50',
            '[&_.ant-table-thead_th]:text-stone-600',
            '[&_.ant-table-thead_th]:font-medium',
            '[&_.ant-table-thead_th]:border-b-stone-200'
          )}
        />
      </div>

      {/* Footer */}
      <div className="px-6 py-3 bg-stone-50 border-t border-stone-100 text-center">
        <Text type="secondary" className="text-xs">
          {t('generatedBy')} - {new Date().toLocaleString()}
        </Text>
      </div>
    </Card>
  );
}

export default ReportPreview;
