export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      ai_conversations: {
        Row: {
          created_at: string;
          id_conversation: string;
          id_shop: string;
          id_user: string;
          last_message_at: string | null;
          status: string | null;
          title: string | null;
          total_credits_used: number | null;
          total_messages: number | null;
          total_tokens_used: number | null;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          id_conversation?: string;
          id_shop: string;
          id_user: string;
          last_message_at?: string | null;
          status?: string | null;
          title?: string | null;
          total_credits_used?: number | null;
          total_messages?: number | null;
          total_tokens_used?: number | null;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          id_conversation?: string;
          id_shop?: string;
          id_user?: string;
          last_message_at?: string | null;
          status?: string | null;
          title?: string | null;
          total_credits_used?: number | null;
          total_messages?: number | null;
          total_tokens_used?: number | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      ai_credit_allocations: {
        Row: {
          allocated_credits: number;
          created_at: string;
          created_by: string;
          id_allocation: string;
          id_credit_pool: string;
          id_shop: string;
          id_user: string;
          updated_at: string;
          used_credits: number | null;
        };
        Insert: {
          allocated_credits: number;
          created_at?: string;
          created_by: string;
          id_allocation?: string;
          id_credit_pool: string;
          id_shop: string;
          id_user: string;
          updated_at?: string;
          used_credits?: number | null;
        };
        Update: {
          allocated_credits?: number;
          created_at?: string;
          created_by?: string;
          id_allocation?: string;
          id_credit_pool?: string;
          id_shop?: string;
          id_user?: string;
          updated_at?: string;
          used_credits?: number | null;
        };
        Relationships: [];
      };
      ai_credit_pools: {
        Row: {
          created_at: string;
          id_credit_pool: string;
          id_shop: string;
          owner_credits: number;
          owner_overflow_used: number | null;
          owner_used: number | null;
          period_end: string;
          period_start: string;
          staff_pool_credits: number;
          staff_pool_used: number | null;
          total_credits: number;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          id_credit_pool?: string;
          id_shop: string;
          owner_credits: number;
          owner_overflow_used?: number | null;
          owner_used?: number | null;
          period_end: string;
          period_start: string;
          staff_pool_credits: number;
          staff_pool_used?: number | null;
          total_credits: number;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          id_credit_pool?: string;
          id_shop?: string;
          owner_credits?: number;
          owner_overflow_used?: number | null;
          owner_used?: number | null;
          period_end?: string;
          period_start?: string;
          staff_pool_credits?: number;
          staff_pool_used?: number | null;
          total_credits?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      ai_messages: {
        Row: {
          content: string;
          created_at: string;
          credits_used: number | null;
          has_operation: boolean | null;
          id_conversation: string;
          id_message: string;
          id_shop: string;
          id_user: string;
          metadata: Json | null;
          operation_approved: boolean | null;
          role: string;
          tokens_used: number | null;
        };
        Insert: {
          content: string;
          created_at?: string;
          credits_used?: number | null;
          has_operation?: boolean | null;
          id_conversation: string;
          id_message?: string;
          id_shop: string;
          id_user: string;
          metadata?: Json | null;
          operation_approved?: boolean | null;
          role: string;
          tokens_used?: number | null;
        };
        Update: {
          content?: string;
          created_at?: string;
          credits_used?: number | null;
          has_operation?: boolean | null;
          id_conversation?: string;
          id_message?: string;
          id_shop?: string;
          id_user?: string;
          metadata?: Json | null;
          operation_approved?: boolean | null;
          role?: string;
          tokens_used?: number | null;
        };
        Relationships: [];
      };
      ai_operations: {
        Row: {
          approved_at: string | null;
          approved_by: string | null;
          created_at: string;
          error_message: string | null;
          executed_at: string | null;
          id_conversation: string;
          id_message: string;
          id_operation: string;
          id_shop: string;
          id_user: string;
          operation_type: string;
          query_executed: string | null;
          record_id: string | null;
          rejected_at: string | null;
          rejected_by: string | null;
          rejection_reason: string | null;
          requires_approval: boolean;
          rows_affected: number | null;
          status: string;
          table_name: string;
        };
        Insert: {
          approved_at?: string | null;
          approved_by?: string | null;
          created_at?: string;
          error_message?: string | null;
          executed_at?: string | null;
          id_conversation: string;
          id_message: string;
          id_operation?: string;
          id_shop: string;
          id_user: string;
          operation_type: string;
          query_executed?: string | null;
          record_id?: string | null;
          rejected_at?: string | null;
          rejected_by?: string | null;
          rejection_reason?: string | null;
          requires_approval: boolean;
          rows_affected?: number | null;
          status: string;
          table_name: string;
        };
        Update: {
          approved_at?: string | null;
          approved_by?: string | null;
          created_at?: string;
          error_message?: string | null;
          executed_at?: string | null;
          id_conversation?: string;
          id_message?: string;
          id_operation?: string;
          id_shop?: string;
          id_user?: string;
          operation_type?: string;
          query_executed?: string | null;
          record_id?: string | null;
          rejected_at?: string | null;
          rejected_by?: string | null;
          rejection_reason?: string | null;
          requires_approval?: boolean;
          rows_affected?: number | null;
          status?: string;
          table_name?: string;
        };
        Relationships: [];
      };
      ai_table_permissions: {
        Row: {
          allowed_columns_read: string[] | null;
          allowed_columns_write: string[] | null;
          can_delete: boolean | null;
          can_insert: boolean | null;
          can_read: boolean | null;
          can_update: boolean | null;
          created_at: string;
          data_guide: string | null;
          id_permission: string;
          required_user_permission: string | null;
          table_name: string;
          updated_at: string;
        };
        Insert: {
          allowed_columns_read?: string[] | null;
          allowed_columns_write?: string[] | null;
          can_delete?: boolean | null;
          can_insert?: boolean | null;
          can_read?: boolean | null;
          can_update?: boolean | null;
          created_at?: string;
          data_guide?: string | null;
          id_permission?: string;
          required_user_permission?: string | null;
          table_name: string;
          updated_at?: string;
        };
        Update: {
          allowed_columns_read?: string[] | null;
          allowed_columns_write?: string[] | null;
          can_delete?: boolean | null;
          can_insert?: boolean | null;
          can_read?: boolean | null;
          can_update?: boolean | null;
          created_at?: string;
          data_guide?: string | null;
          id_permission?: string;
          required_user_permission?: string | null;
          table_name?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      ai_token_usage: {
        Row: {
          cost_usd: number | null;
          created_at: string;
          credits_charged: number;
          id_conversation: string;
          id_message: string;
          id_shop: string;
          id_usage: string;
          id_user: string;
          input_tokens: number;
          model: string;
          output_tokens: number;
          total_tokens: number;
        };
        Insert: {
          cost_usd?: number | null;
          created_at?: string;
          credits_charged: number;
          id_conversation: string;
          id_message: string;
          id_shop: string;
          id_usage?: string;
          id_user: string;
          input_tokens: number;
          model: string;
          output_tokens: number;
          total_tokens: number;
        };
        Update: {
          cost_usd?: number | null;
          created_at?: string;
          credits_charged?: number;
          id_conversation?: string;
          id_message?: string;
          id_shop?: string;
          id_usage?: string;
          id_user?: string;
          input_tokens?: number;
          model?: string;
          output_tokens?: number;
          total_tokens?: number;
        };
        Relationships: [];
      };
      budget_allocations: {
        Row: {
          allocated_amount: number;
          created_at: string;
          created_by: string;
          id_budget_allocation: string;
          id_budget_category: string;
          id_shop: string;
          id_user: string | null;
          notes: string | null;
          period_end: string;
          period_start: string;
          remaining_amount: number | null;
          rollover_amount: number | null;
          rollover_enabled: boolean | null;
          status: string | null;
          updated_at: string;
          updated_by: string | null;
          used_amount: number | null;
        };
        Insert: {
          allocated_amount: number;
          created_at?: string;
          created_by: string;
          id_budget_allocation?: string;
          id_budget_category: string;
          id_shop: string;
          id_user?: string | null;
          notes?: string | null;
          period_end: string;
          period_start: string;
          remaining_amount?: number | null;
          rollover_amount?: number | null;
          rollover_enabled?: boolean | null;
          status?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          used_amount?: number | null;
        };
        Update: {
          allocated_amount?: number;
          created_at?: string;
          created_by?: string;
          id_budget_allocation?: string;
          id_budget_category?: string;
          id_shop?: string;
          id_user?: string | null;
          notes?: string | null;
          period_end?: string;
          period_start?: string;
          remaining_amount?: number | null;
          rollover_amount?: number | null;
          rollover_enabled?: boolean | null;
          status?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          used_amount?: number | null;
        };
        Relationships: [];
      };
      budget_categories: {
        Row: {
          approval_threshold: number | null;
          budget_type: string;
          category_name: string;
          created_at: string;
          created_by: string;
          default_amount: number | null;
          default_frequency: string | null;
          deleted_at: string | null;
          description: string | null;
          id_budget_category: string;
          id_shop: string;
          is_active: boolean | null;
          requires_approval: boolean | null;
          sort_order: number | null;
          updated_at: string;
        };
        Insert: {
          approval_threshold?: number | null;
          budget_type: string;
          category_name: string;
          created_at?: string;
          created_by: string;
          default_amount?: number | null;
          default_frequency?: string | null;
          deleted_at?: string | null;
          description?: string | null;
          id_budget_category?: string;
          id_shop: string;
          is_active?: boolean | null;
          requires_approval?: boolean | null;
          sort_order?: number | null;
          updated_at?: string;
        };
        Update: {
          approval_threshold?: number | null;
          budget_type?: string;
          category_name?: string;
          created_at?: string;
          created_by?: string;
          default_amount?: number | null;
          default_frequency?: string | null;
          deleted_at?: string | null;
          description?: string | null;
          id_budget_category?: string;
          id_shop?: string;
          is_active?: boolean | null;
          requires_approval?: boolean | null;
          sort_order?: number | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      budget_transactions: {
        Row: {
          amount: number;
          approval_status: string | null;
          approved_at: string | null;
          approved_by: string | null;
          created_at: string;
          created_by: string;
          description: string;
          id_budget_allocation: string;
          id_expense: string | null;
          id_shop: string;
          id_transaction: string;
          sequence_number: number;
          transaction_type: string;
        };
        Insert: {
          amount: number;
          approval_status?: string | null;
          approved_at?: string | null;
          approved_by?: string | null;
          created_at?: string;
          created_by: string;
          description: string;
          id_budget_allocation: string;
          id_expense?: string | null;
          id_shop: string;
          id_transaction?: string;
          sequence_number?: number;
          transaction_type: string;
        };
        Update: {
          amount?: number;
          approval_status?: string | null;
          approved_at?: string | null;
          approved_by?: string | null;
          created_at?: string;
          created_by?: string;
          description?: string;
          id_budget_allocation?: string;
          id_expense?: string | null;
          id_shop?: string;
          id_transaction?: string;
          sequence_number?: number;
          transaction_type?: string;
        };
        Relationships: [];
      };
      courier_companies: {
        Row: {
          company_name: string;
          contact_person: string | null;
          created_at: string;
          created_by: string;
          current_balance: number;
          deleted_at: string | null;
          email: string | null;
          id_courier: string;
          id_shop: string;
          notes: string | null;
          phone: string | null;
          status: string | null;
          updated_at: string;
          updated_by: string | null;
          version: number;
          website: string | null;
        };
        Insert: {
          company_name: string;
          contact_person?: string | null;
          created_at?: string;
          created_by: string;
          current_balance?: number;
          deleted_at?: string | null;
          email?: string | null;
          id_courier?: string;
          id_shop: string;
          notes?: string | null;
          phone?: string | null;
          status?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          version?: number;
          website?: string | null;
        };
        Update: {
          company_name?: string;
          contact_person?: string | null;
          created_at?: string;
          created_by?: string;
          current_balance?: number;
          deleted_at?: string | null;
          email?: string | null;
          id_courier?: string;
          id_shop?: string;
          notes?: string | null;
          phone?: string | null;
          status?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          version?: number;
          website?: string | null;
        };
        Relationships: [];
      };
      courier_payments: {
        Row: {
          amount: number;
          cheque_bank: string | null;
          cheque_cleared_date: string | null;
          cheque_date: string | null;
          cheque_number: string | null;
          cheque_status: string | null;
          created_at: string;
          created_by: string;
          id_courier: string;
          id_payment: string;
          id_shop: string;
          notes: string | null;
          payment_date: string;
          payment_type: string;
        };
        Insert: {
          amount: number;
          cheque_bank?: string | null;
          cheque_cleared_date?: string | null;
          cheque_date?: string | null;
          cheque_number?: string | null;
          cheque_status?: string | null;
          created_at?: string;
          created_by: string;
          id_courier: string;
          id_payment?: string;
          id_shop: string;
          notes?: string | null;
          payment_date: string;
          payment_type: string;
        };
        Update: {
          amount?: number;
          cheque_bank?: string | null;
          cheque_cleared_date?: string | null;
          cheque_date?: string | null;
          cheque_number?: string | null;
          cheque_status?: string | null;
          created_at?: string;
          created_by?: string;
          id_courier?: string;
          id_payment?: string;
          id_shop?: string;
          notes?: string | null;
          payment_date?: string;
          payment_type?: string;
        };
        Relationships: [];
      };
      courier_transactions: {
        Row: {
          balance_after: number;
          created_at: string;
          created_by: string;
          credit_amount: number;
          debit_amount: number;
          description: string | null;
          id_courier: string;
          id_shop: string;
          id_transaction: string;
          reference_id: string | null;
          reference_type: string | null;
          sequence_number: number;
          transaction_type: string;
        };
        Insert: {
          balance_after: number;
          created_at?: string;
          created_by: string;
          credit_amount?: number;
          debit_amount?: number;
          description?: string | null;
          id_courier: string;
          id_shop: string;
          id_transaction?: string;
          reference_id?: string | null;
          reference_type?: string | null;
          sequence_number?: number;
          transaction_type: string;
        };
        Update: {
          balance_after?: number;
          created_at?: string;
          created_by?: string;
          credit_amount?: number;
          debit_amount?: number;
          description?: string | null;
          id_courier?: string;
          id_shop?: string;
          id_transaction?: string;
          reference_id?: string | null;
          reference_type?: string | null;
          sequence_number?: number;
          transaction_type?: string;
        };
        Relationships: [];
      };
      customer_transactions: {
        Row: {
          balance_after: number;
          created_at: string;
          created_by: string;
          credit_amount: number;
          debit_amount: number;
          description: string | null;
          id_customer: string;
          id_shop: string;
          id_transaction: string;
          reference_id: string | null;
          reference_type: string | null;
          sequence_number: number;
          transaction_type: string;
        };
        Insert: {
          balance_after: number;
          created_at?: string;
          created_by: string;
          credit_amount?: number;
          debit_amount?: number;
          description?: string | null;
          id_customer: string;
          id_shop: string;
          id_transaction?: string;
          reference_id?: string | null;
          reference_type?: string | null;
          sequence_number?: number;
          transaction_type: string;
        };
        Update: {
          balance_after?: number;
          created_at?: string;
          created_by?: string;
          credit_amount?: number;
          debit_amount?: number;
          description?: string | null;
          id_customer?: string;
          id_shop?: string;
          id_transaction?: string;
          reference_id?: string | null;
          reference_type?: string | null;
          sequence_number?: number;
          transaction_type?: string;
        };
        Relationships: [];
      };
      customers: {
        Row: {
          address: string | null;
          client_type: string | null;
          created_at: string;
          created_by: string;
          current_balance: number;
          deleted_at: string | null;
          email: string | null;
          financial_status: string | null;
          full_name: string;
          id_customer: string;
          id_shop: string;
          notes: string | null;
          phone: string | null;
          total_payments: number;
          total_purchases: number;
          updated_at: string;
          updated_by: string | null;
          version: number;
        };
        Insert: {
          address?: string | null;
          client_type?: string | null;
          created_at?: string;
          created_by: string;
          current_balance?: number;
          deleted_at?: string | null;
          email?: string | null;
          financial_status?: string | null;
          full_name: string;
          id_customer?: string;
          id_shop: string;
          notes?: string | null;
          phone?: string | null;
          total_payments?: number;
          total_purchases?: number;
          updated_at?: string;
          updated_by?: string | null;
          version?: number;
        };
        Update: {
          address?: string | null;
          client_type?: string | null;
          created_at?: string;
          created_by?: string;
          current_balance?: number;
          deleted_at?: string | null;
          email?: string | null;
          financial_status?: string | null;
          full_name?: string;
          id_customer?: string;
          id_shop?: string;
          notes?: string | null;
          phone?: string | null;
          total_payments?: number;
          total_purchases?: number;
          updated_at?: string;
          updated_by?: string | null;
          version?: number;
        };
        Relationships: [];
      };
      deliveries: {
        Row: {
          cost_paid_by: string;
          created_at: string;
          created_by: string;
          delivered_date: string | null;
          delivery_address: string | null;
          delivery_cost: number;
          estimated_delivery_date: string | null;
          id_courier: string;
          id_delivery: string;
          id_sale: string;
          id_shop: string;
          notes: string | null;
          recipient_name: string | null;
          shipped_date: string | null;
          status: string | null;
          tracking_number: string | null;
          updated_at: string;
          updated_by: string | null;
        };
        Insert: {
          cost_paid_by: string;
          created_at?: string;
          created_by: string;
          delivered_date?: string | null;
          delivery_address?: string | null;
          delivery_cost: number;
          estimated_delivery_date?: string | null;
          id_courier: string;
          id_delivery?: string;
          id_sale: string;
          id_shop: string;
          notes?: string | null;
          recipient_name?: string | null;
          shipped_date?: string | null;
          status?: string | null;
          tracking_number?: string | null;
          updated_at?: string;
          updated_by?: string | null;
        };
        Update: {
          cost_paid_by?: string;
          created_at?: string;
          created_by?: string;
          delivered_date?: string | null;
          delivery_address?: string | null;
          delivery_cost?: number;
          estimated_delivery_date?: string | null;
          id_courier?: string;
          id_delivery?: string;
          id_sale?: string;
          id_shop?: string;
          notes?: string | null;
          recipient_name?: string | null;
          shipped_date?: string | null;
          status?: string | null;
          tracking_number?: string | null;
          updated_at?: string;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      expense_approvals: {
        Row: {
          action: string;
          action_at: string;
          action_by: string;
          comments: string | null;
          id_approval: string;
          id_expense: string;
          id_shop: string;
          new_status: string | null;
          previous_status: string | null;
        };
        Insert: {
          action: string;
          action_at?: string;
          action_by: string;
          comments?: string | null;
          id_approval?: string;
          id_expense: string;
          id_shop: string;
          new_status?: string | null;
          previous_status?: string | null;
        };
        Update: {
          action?: string;
          action_at?: string;
          action_by?: string;
          comments?: string | null;
          id_approval?: string;
          id_expense?: string;
          id_shop?: string;
          new_status?: string | null;
          previous_status?: string | null;
        };
        Relationships: [];
      };
      expense_categories: {
        Row: {
          category_name: string;
          category_type: string;
          created_at: string;
          created_by: string;
          deleted_at: string | null;
          description: string | null;
          id_expense_category: string;
          id_shop: string;
          is_active: boolean | null;
          is_taxable: boolean | null;
          sort_order: number | null;
          updated_at: string;
        };
        Insert: {
          category_name: string;
          category_type: string;
          created_at?: string;
          created_by: string;
          deleted_at?: string | null;
          description?: string | null;
          id_expense_category?: string;
          id_shop: string;
          is_active?: boolean | null;
          is_taxable?: boolean | null;
          sort_order?: number | null;
          updated_at?: string;
        };
        Update: {
          category_name?: string;
          category_type?: string;
          created_at?: string;
          created_by?: string;
          deleted_at?: string | null;
          description?: string | null;
          id_expense_category?: string;
          id_shop?: string;
          is_active?: boolean | null;
          is_taxable?: boolean | null;
          sort_order?: number | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      expense_payments: {
        Row: {
          amount: number;
          cheque_bank: string | null;
          cheque_cleared_date: string | null;
          cheque_date: string | null;
          cheque_number: string | null;
          cheque_status: string | null;
          created_at: string;
          created_by: string;
          id_expense: string;
          id_payment: string;
          id_shop: string;
          notes: string | null;
          payment_date: string;
          payment_type: string;
        };
        Insert: {
          amount: number;
          cheque_bank?: string | null;
          cheque_cleared_date?: string | null;
          cheque_date?: string | null;
          cheque_number?: string | null;
          cheque_status?: string | null;
          created_at?: string;
          created_by: string;
          id_expense: string;
          id_payment?: string;
          id_shop: string;
          notes?: string | null;
          payment_date: string;
          payment_type: string;
        };
        Update: {
          amount?: number;
          cheque_bank?: string | null;
          cheque_cleared_date?: string | null;
          cheque_date?: string | null;
          cheque_number?: string | null;
          cheque_status?: string | null;
          created_at?: string;
          created_by?: string;
          id_expense?: string;
          id_payment?: string;
          id_shop?: string;
          notes?: string | null;
          payment_date?: string;
          payment_type?: string;
        };
        Relationships: [];
      };
      expenses: {
        Row: {
          amount: number;
          approval_status: string | null;
          approval_threshold_exceeded: boolean | null;
          approved_at: string | null;
          approved_by: string | null;
          created_at: string;
          created_by: string;
          deleted_at: string | null;
          description: string;
          due_date: string | null;
          expense_date: string;
          expense_number: string;
          id_expense: string;
          id_expense_category: string;
          id_file_upload: string | null;
          id_recurring_expense: string | null;
          id_shop: string;
          notes: string | null;
          paid_amount: number | null;
          payment_status: string | null;
          rejected_at: string | null;
          rejected_by: string | null;
          rejection_reason: string | null;
          updated_at: string;
          updated_by: string | null;
          vendor_name: string | null;
        };
        Insert: {
          amount: number;
          approval_status?: string | null;
          approval_threshold_exceeded?: boolean | null;
          approved_at?: string | null;
          approved_by?: string | null;
          created_at?: string;
          created_by: string;
          deleted_at?: string | null;
          description: string;
          due_date?: string | null;
          expense_date: string;
          expense_number: string;
          id_expense?: string;
          id_expense_category: string;
          id_file_upload?: string | null;
          id_recurring_expense?: string | null;
          id_shop: string;
          notes?: string | null;
          paid_amount?: number | null;
          payment_status?: string | null;
          rejected_at?: string | null;
          rejected_by?: string | null;
          rejection_reason?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          vendor_name?: string | null;
        };
        Update: {
          amount?: number;
          approval_status?: string | null;
          approval_threshold_exceeded?: boolean | null;
          approved_at?: string | null;
          approved_by?: string | null;
          created_at?: string;
          created_by?: string;
          deleted_at?: string | null;
          description?: string;
          due_date?: string | null;
          expense_date?: string;
          expense_number?: string;
          id_expense?: string;
          id_expense_category?: string;
          id_file_upload?: string | null;
          id_recurring_expense?: string | null;
          id_shop?: string;
          notes?: string | null;
          paid_amount?: number | null;
          payment_status?: string | null;
          rejected_at?: string | null;
          rejected_by?: string | null;
          rejection_reason?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          vendor_name?: string | null;
        };
        Relationships: [];
      };
      inventory_items: {
        Row: {
          barcode: string | null;
          created_at: string;
          created_by: string;
          currency: string;
          deleted_at: string | null;
          description: string | null;
          gold_color: string | null;
          id_category: string | null;
          id_item: string;
          id_metal_purity: string | null;
          id_metal_type: string | null;
          id_purchase: string | null;
          id_recycled_item: string | null;
          id_shop: string;
          id_size: string | null;
          id_stone_type: string | null;
          item_name: string;
          item_type: string;
          ownership_type: string;
          purchase_price: number;
          sku: string | null;
          source_type: string;
          status: string;
          stone_weight_carats: number | null;
          updated_at: string;
          updated_by: string | null;
          version: number;
          weight_grams: number;
        };
        Insert: {
          barcode?: string | null;
          created_at?: string;
          created_by: string;
          currency: string;
          deleted_at?: string | null;
          description?: string | null;
          gold_color?: string | null;
          id_category?: string | null;
          id_item?: string;
          id_metal_purity?: string | null;
          id_metal_type?: string | null;
          id_purchase?: string | null;
          id_recycled_item?: string | null;
          id_shop: string;
          id_size?: string | null;
          id_stone_type?: string | null;
          item_name: string;
          item_type?: string;
          ownership_type?: string;
          purchase_price: number;
          sku?: string | null;
          source_type: string;
          status?: string;
          stone_weight_carats?: number | null;
          updated_at?: string;
          updated_by?: string | null;
          version?: number;
          weight_grams: number;
        };
        Update: {
          barcode?: string | null;
          created_at?: string;
          created_by?: string;
          currency?: string;
          deleted_at?: string | null;
          description?: string | null;
          gold_color?: string | null;
          id_category?: string | null;
          id_item?: string;
          id_metal_purity?: string | null;
          id_metal_type?: string | null;
          id_purchase?: string | null;
          id_recycled_item?: string | null;
          id_shop?: string;
          id_size?: string | null;
          id_stone_type?: string | null;
          item_name?: string;
          item_type?: string;
          ownership_type?: string;
          purchase_price?: number;
          sku?: string | null;
          source_type?: string;
          status?: string;
          stone_weight_carats?: number | null;
          updated_at?: string;
          updated_by?: string | null;
          version?: number;
          weight_grams?: number;
        };
        Relationships: [];
      };
      item_stones: {
        Row: {
          clarity: string | null;
          color: string | null;
          created_at: string;
          cut: string | null;
          estimated_value: number | null;
          id_item: string;
          id_item_stone: string;
          id_shop: string;
          id_stone_type: string;
          notes: string | null;
          position: string | null;
          stone_count: number | null;
          weight_carats: number;
        };
        Insert: {
          clarity?: string | null;
          color?: string | null;
          created_at?: string;
          cut?: string | null;
          estimated_value?: number | null;
          id_item: string;
          id_item_stone?: string;
          id_shop: string;
          id_stone_type: string;
          notes?: string | null;
          position?: string | null;
          stone_count?: number | null;
          weight_carats: number;
        };
        Update: {
          clarity?: string | null;
          color?: string | null;
          created_at?: string;
          cut?: string | null;
          estimated_value?: number | null;
          id_item?: string;
          id_item_stone?: string;
          id_shop?: string;
          id_stone_type?: string;
          notes?: string | null;
          position?: string | null;
          stone_count?: number | null;
          weight_carats?: number;
        };
        Relationships: [];
      };
      metal_prices: {
        Row: {
          buy_price_per_gram: number | null;
          created_at: string;
          created_by: string;
          currency: string;
          id_metal_purity: string | null;
          id_metal_type: string;
          id_price: string;
          id_shop: string;
          notes: string | null;
          price_date: string;
          price_per_gram: number;
          sell_price_per_gram: number | null;
          source: string | null;
        };
        Insert: {
          buy_price_per_gram?: number | null;
          created_at?: string;
          created_by: string;
          currency: string;
          id_metal_purity?: string | null;
          id_metal_type: string;
          id_price?: string;
          id_shop: string;
          notes?: string | null;
          price_date: string;
          price_per_gram: number;
          sell_price_per_gram?: number | null;
          source?: string | null;
        };
        Update: {
          buy_price_per_gram?: number | null;
          created_at?: string;
          created_by?: string;
          currency?: string;
          id_metal_purity?: string | null;
          id_metal_type?: string;
          id_price?: string;
          id_shop?: string;
          notes?: string | null;
          price_date?: string;
          price_per_gram?: number;
          sell_price_per_gram?: number | null;
          source?: string | null;
        };
        Relationships: [];
      };
      metal_purities: {
        Row: {
          created_at: string;
          created_by: string;
          deleted_at: string | null;
          fineness: number;
          id_metal_type: string;
          id_purity: string;
          id_shop: string;
          purity_name: string;
          purity_percentage: number;
          sort_order: number | null;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          created_by: string;
          deleted_at?: string | null;
          fineness: number;
          id_metal_type: string;
          id_purity?: string;
          id_shop: string;
          purity_name: string;
          purity_percentage: number;
          sort_order?: number | null;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          created_by?: string;
          deleted_at?: string | null;
          fineness?: number;
          id_metal_type?: string;
          id_purity?: string;
          id_shop?: string;
          purity_name?: string;
          purity_percentage?: number;
          sort_order?: number | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      metal_types: {
        Row: {
          created_at: string;
          created_by: string;
          deleted_at: string | null;
          description: string | null;
          id_metal_type: string;
          id_shop: string;
          metal_name: string;
          sort_order: number | null;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          created_by: string;
          deleted_at?: string | null;
          description?: string | null;
          id_metal_type?: string;
          id_shop: string;
          metal_name: string;
          sort_order?: number | null;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          created_by?: string;
          deleted_at?: string | null;
          description?: string | null;
          id_metal_type?: string;
          id_shop?: string;
          metal_name?: string;
          sort_order?: number | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      neighbor_shops: {
        Row: {
          id_neighbor: string;
          id_shop: string;
          neighbor_type: string;
          id_neighbor_shop: string | null;
          external_shop_name: string | null;
          external_shop_phone: string | null;
          external_shop_address: string | null;
          status: string | null;
          balance_items_value: number | null;
          balance_gold_grams: number | null;
          balance_gold_value: number | null;
          balance_money: number | null;
          balance_total: number | null;
          notes: string | null;
          approved_by: string | null;
          approved_at: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
          version: number;
        };
        Insert: {
          id_neighbor?: string;
          id_shop: string;
          neighbor_type: string;
          id_neighbor_shop?: string | null;
          external_shop_name?: string | null;
          external_shop_phone?: string | null;
          external_shop_address?: string | null;
          status?: string | null;
          balance_items_value?: number | null;
          balance_gold_grams?: number | null;
          balance_gold_value?: number | null;
          balance_money?: number | null;
          balance_total?: number | null;
          notes?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
          version?: number;
        };
        Update: {
          id_neighbor?: string;
          id_shop?: string;
          neighbor_type?: string;
          id_neighbor_shop?: string | null;
          external_shop_name?: string | null;
          external_shop_phone?: string | null;
          external_shop_address?: string | null;
          status?: string | null;
          balance_items_value?: number | null;
          balance_gold_grams?: number | null;
          balance_gold_value?: number | null;
          balance_money?: number | null;
          balance_total?: number | null;
          notes?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
          version?: number;
        };
        Relationships: [];
      };
      product_categories: {
        Row: {
          category_name: string;
          created_at: string;
          created_by: string;
          deleted_at: string | null;
          description: string | null;
          id_category: string;
          id_shop: string;
          sort_order: number | null;
          updated_at: string;
        };
        Insert: {
          category_name: string;
          created_at?: string;
          created_by: string;
          deleted_at?: string | null;
          description?: string | null;
          id_category?: string;
          id_shop: string;
          sort_order?: number | null;
          updated_at?: string;
        };
        Update: {
          category_name?: string;
          created_at?: string;
          created_by?: string;
          deleted_at?: string | null;
          description?: string | null;
          id_category?: string;
          id_shop?: string;
          sort_order?: number | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      product_sizes: {
        Row: {
          created_at: string;
          created_by: string;
          id_category: string;
          id_shop: string;
          id_size: string;
          size_name: string;
          size_system: string | null;
          size_value: string | null;
          sort_order: number | null;
        };
        Insert: {
          created_at?: string;
          created_by: string;
          id_category: string;
          id_shop: string;
          id_size?: string;
          size_name: string;
          size_system?: string | null;
          size_value?: string | null;
          sort_order?: number | null;
        };
        Update: {
          created_at?: string;
          created_by?: string;
          id_category?: string;
          id_shop?: string;
          id_size?: string;
          size_name?: string;
          size_system?: string | null;
          size_value?: string | null;
          sort_order?: number | null;
        };
        Relationships: [];
      };
      purchases: {
        Row: {
          created_at: string;
          created_by: string;
          currency: string;
          deleted_at: string | null;
          id_purchase: string;
          id_shop: string;
          id_supplier: string;
          invoice_number: string | null;
          notes: string | null;
          paid_amount: number | null;
          payment_status: string | null;
          purchase_date: string;
          purchase_number: string;
          total_amount: number;
          total_items: number | null;
          total_weight_grams: number | null;
          updated_at: string;
          updated_by: string | null;
          version: number;
        };
        Insert: {
          created_at?: string;
          created_by: string;
          currency: string;
          deleted_at?: string | null;
          id_purchase?: string;
          id_shop: string;
          id_supplier: string;
          invoice_number?: string | null;
          notes?: string | null;
          paid_amount?: number | null;
          payment_status?: string | null;
          purchase_date: string;
          purchase_number: string;
          total_amount: number;
          total_items?: number | null;
          total_weight_grams?: number | null;
          updated_at?: string;
          updated_by?: string | null;
          version?: number;
        };
        Update: {
          created_at?: string;
          created_by?: string;
          currency?: string;
          deleted_at?: string | null;
          id_purchase?: string;
          id_shop?: string;
          id_supplier?: string;
          invoice_number?: string | null;
          notes?: string | null;
          paid_amount?: number | null;
          payment_status?: string | null;
          purchase_date?: string;
          purchase_number?: string;
          total_amount?: number;
          total_items?: number | null;
          total_weight_grams?: number | null;
          updated_at?: string;
          updated_by?: string | null;
          version?: number;
        };
        Relationships: [];
      };
      recycled_items: {
        Row: {
          assessed_value: number;
          created_at: string;
          created_by: string;
          currency: string;
          deleted_at: string | null;
          id_customer: string;
          id_inventory_item_created: string | null;
          id_metal_purity: string | null;
          id_metal_type: string | null;
          id_recycled_item: string;
          id_shop: string;
          id_supplier_sold_to: string | null;
          notes: string | null;
          paid_amount: number | null;
          payment_status: string | null;
          recycled_date: string;
          resale_date: string | null;
          resale_price: number | null;
          sold_to_supplier_date: string | null;
          status: string | null;
          stone_weight_carats: number | null;
          updated_at: string;
          updated_by: string | null;
          version: number;
          weight_grams: number;
        };
        Insert: {
          assessed_value: number;
          created_at?: string;
          created_by: string;
          currency: string;
          deleted_at?: string | null;
          id_customer: string;
          id_inventory_item_created?: string | null;
          id_metal_purity?: string | null;
          id_metal_type?: string | null;
          id_recycled_item?: string;
          id_shop: string;
          id_supplier_sold_to?: string | null;
          notes?: string | null;
          paid_amount?: number | null;
          payment_status?: string | null;
          recycled_date: string;
          resale_date?: string | null;
          resale_price?: number | null;
          sold_to_supplier_date?: string | null;
          status?: string | null;
          stone_weight_carats?: number | null;
          updated_at?: string;
          updated_by?: string | null;
          version?: number;
          weight_grams: number;
        };
        Update: {
          assessed_value?: number;
          created_at?: string;
          created_by?: string;
          currency?: string;
          deleted_at?: string | null;
          id_customer?: string;
          id_inventory_item_created?: string | null;
          id_metal_purity?: string | null;
          id_metal_type?: string | null;
          id_recycled_item?: string;
          id_shop?: string;
          id_supplier_sold_to?: string | null;
          notes?: string | null;
          paid_amount?: number | null;
          payment_status?: string | null;
          recycled_date?: string;
          resale_date?: string | null;
          resale_price?: number | null;
          sold_to_supplier_date?: string | null;
          status?: string | null;
          stone_weight_carats?: number | null;
          updated_at?: string;
          updated_by?: string | null;
          version?: number;
          weight_grams?: number;
        };
        Relationships: [];
      };
      recurring_expenses: {
        Row: {
          amount: number;
          auto_approve: boolean | null;
          created_at: string;
          created_by: string;
          day_of_month: number | null;
          day_of_week: number | null;
          deleted_at: string | null;
          description: string;
          end_date: string | null;
          frequency: string;
          id_expense_category: string;
          id_recurring_expense: string;
          id_shop: string;
          is_active: boolean | null;
          last_generated_date: string | null;
          next_due_date: string;
          start_date: string;
          updated_at: string;
          updated_by: string | null;
          vendor_name: string | null;
        };
        Insert: {
          amount: number;
          auto_approve?: boolean | null;
          created_at?: string;
          created_by: string;
          day_of_month?: number | null;
          day_of_week?: number | null;
          deleted_at?: string | null;
          description: string;
          end_date?: string | null;
          frequency: string;
          id_expense_category: string;
          id_recurring_expense?: string;
          id_shop: string;
          is_active?: boolean | null;
          last_generated_date?: string | null;
          next_due_date: string;
          start_date: string;
          updated_at?: string;
          updated_by?: string | null;
          vendor_name?: string | null;
        };
        Update: {
          amount?: number;
          auto_approve?: boolean | null;
          created_at?: string;
          created_by?: string;
          day_of_month?: number | null;
          day_of_week?: number | null;
          deleted_at?: string | null;
          description?: string;
          end_date?: string | null;
          frequency?: string;
          id_expense_category?: string;
          id_recurring_expense?: string;
          id_shop?: string;
          is_active?: boolean | null;
          last_generated_date?: string | null;
          next_due_date?: string;
          start_date?: string;
          updated_at?: string;
          updated_by?: string | null;
          vendor_name?: string | null;
        };
        Relationships: [];
      };
      sale_items: {
        Row: {
          created_at: string;
          discount_amount: number | null;
          discount_type: string | null;
          id_item: string;
          id_sale: string;
          id_sale_item: string;
          id_shop: string;
          line_total: number;
          unit_price: number;
        };
        Insert: {
          created_at?: string;
          discount_amount?: number | null;
          discount_type?: string | null;
          id_item: string;
          id_sale: string;
          id_sale_item?: string;
          id_shop: string;
          line_total: number;
          unit_price: number;
        };
        Update: {
          created_at?: string;
          discount_amount?: number | null;
          discount_type?: string | null;
          id_item?: string;
          id_sale?: string;
          id_sale_item?: string;
          id_shop?: string;
          line_total?: number;
          unit_price?: number;
        };
        Relationships: [];
      };
      sale_payments: {
        Row: {
          amount: number;
          cheque_bank: string | null;
          cheque_cleared_date: string | null;
          cheque_date: string | null;
          cheque_number: string | null;
          cheque_status: string | null;
          created_at: string;
          created_by: string;
          id_payment: string;
          id_sale: string;
          id_shop: string;
          notes: string | null;
          payment_date: string;
          payment_type: string;
        };
        Insert: {
          amount: number;
          cheque_bank?: string | null;
          cheque_cleared_date?: string | null;
          cheque_date?: string | null;
          cheque_number?: string | null;
          cheque_status?: string | null;
          created_at?: string;
          created_by: string;
          id_payment?: string;
          id_sale: string;
          id_shop: string;
          notes?: string | null;
          payment_date: string;
          payment_type: string;
        };
        Update: {
          amount?: number;
          cheque_bank?: string | null;
          cheque_cleared_date?: string | null;
          cheque_date?: string | null;
          cheque_number?: string | null;
          cheque_status?: string | null;
          created_at?: string;
          created_by?: string;
          id_payment?: string;
          id_sale?: string;
          id_shop?: string;
          notes?: string | null;
          payment_date?: string;
          payment_type?: string;
        };
        Relationships: [];
      };
      sales: {
        Row: {
          created_at: string;
          created_by: string;
          currency: string;
          deleted_at: string | null;
          discount_amount: number | null;
          discount_type: string | null;
          id_customer: string | null;
          id_sale: string;
          id_shop: string;
          invoice_number: string;
          notes: string | null;
          paid_amount: number | null;
          payment_status: string | null;
          sale_date: string;
          sale_type: string;
          status: string | null;
          subtotal: number;
          tax_amount: number | null;
          total_amount: number;
          updated_at: string;
          updated_by: string | null;
          version: number;
        };
        Insert: {
          created_at?: string;
          created_by: string;
          currency: string;
          deleted_at?: string | null;
          discount_amount?: number | null;
          discount_type?: string | null;
          id_customer?: string | null;
          id_sale?: string;
          id_shop: string;
          invoice_number: string;
          notes?: string | null;
          paid_amount?: number | null;
          payment_status?: string | null;
          sale_date: string;
          sale_type?: string;
          status?: string | null;
          subtotal: number;
          tax_amount?: number | null;
          total_amount: number;
          updated_at?: string;
          updated_by?: string | null;
          version?: number;
        };
        Update: {
          created_at?: string;
          created_by?: string;
          currency?: string;
          deleted_at?: string | null;
          discount_amount?: number | null;
          discount_type?: string | null;
          id_customer?: string | null;
          id_sale?: string;
          id_shop?: string;
          invoice_number?: string;
          notes?: string | null;
          paid_amount?: number | null;
          payment_status?: string | null;
          sale_date?: string;
          sale_type?: string;
          status?: string | null;
          subtotal?: number;
          tax_amount?: number | null;
          total_amount?: number;
          updated_at?: string;
          updated_by?: string | null;
          version?: number;
        };
        Relationships: [];
      };
      shop_settings: {
        Row: {
          created_at: string;
          id_setting: string;
          id_shop: string;
          setting_key: string;
          setting_value: Json;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          id_setting?: string;
          id_shop: string;
          setting_key: string;
          setting_value: Json;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          id_setting?: string;
          id_shop?: string;
          setting_key?: string;
          setting_value?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      shops: {
        Row: {
          created_at: string;
          currency: string;
          deleted_at: string | null;
          id_owner: string;
          id_shop: string;
          id_subscription: string;
          language: string;
          shop_logo: string | null;
          shop_name: string;
          storage_used_bytes: number | null;
          timezone: string;
          updated_at: string;
          version: number;
        };
        Insert: {
          created_at?: string;
          currency?: string;
          deleted_at?: string | null;
          id_owner: string;
          id_shop?: string;
          id_subscription: string;
          language?: string;
          shop_logo?: string | null;
          shop_name: string;
          storage_used_bytes?: number | null;
          timezone?: string;
          updated_at?: string;
          version?: number;
        };
        Update: {
          created_at?: string;
          currency?: string;
          deleted_at?: string | null;
          id_owner?: string;
          id_shop?: string;
          id_subscription?: string;
          language?: string;
          shop_logo?: string | null;
          shop_name?: string;
          storage_used_bytes?: number | null;
          timezone?: string;
          updated_at?: string;
          version?: number;
        };
        Relationships: [];
      };
      shop_transfer_items: {
        Row: {
          id_transfer_item: string;
          id_shop: string;
          id_transfer: string;
          id_inventory_item: string;
          item_name: string;
          item_sku: string | null;
          weight_grams: number | null;
          metal_type: string | null;
          metal_purity: string | null;
          category_name: string | null;
          item_value: number;
          status: string | null;
          returned_at: string | null;
          returned_by: string | null;
          notes: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
          updated_by: string | null;
        };
        Insert: {
          id_transfer_item?: string;
          id_shop: string;
          id_transfer: string;
          id_inventory_item: string;
          item_name: string;
          item_sku?: string | null;
          weight_grams?: number | null;
          metal_type?: string | null;
          metal_purity?: string | null;
          category_name?: string | null;
          item_value: number;
          status?: string | null;
          returned_at?: string | null;
          returned_by?: string | null;
          notes?: string | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
          updated_by?: string | null;
        };
        Update: {
          id_transfer_item?: string;
          id_shop?: string;
          id_transfer?: string;
          id_inventory_item?: string;
          item_name?: string;
          item_sku?: string | null;
          weight_grams?: number | null;
          metal_type?: string | null;
          metal_purity?: string | null;
          category_name?: string | null;
          item_value?: number;
          status?: string | null;
          returned_at?: string | null;
          returned_by?: string | null;
          notes?: string | null;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      shop_transfers: {
        Row: {
          id_transfer: string;
          id_shop: string;
          transfer_number: string;
          id_neighbor: string;
          direction: string;
          total_items_count: number | null;
          total_items_value: number | null;
          gold_grams: number | null;
          gold_value: number | null;
          money_amount: number | null;
          total_value: number | null;
          status: string;
          due_date: string | null;
          return_date: string | null;
          notes: string | null;
          approved_by: string | null;
          approved_at: string | null;
          rejected_by: string | null;
          rejected_at: string | null;
          rejection_reason: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
          version: number;
        };
        Insert: {
          id_transfer?: string;
          id_shop: string;
          transfer_number?: string;
          id_neighbor: string;
          direction: string;
          total_items_count?: number | null;
          total_items_value?: number | null;
          gold_grams?: number | null;
          gold_value?: number | null;
          money_amount?: number | null;
          total_value?: number | null;
          status?: string;
          due_date?: string | null;
          return_date?: string | null;
          notes?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          rejected_by?: string | null;
          rejected_at?: string | null;
          rejection_reason?: string | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
          version?: number;
        };
        Update: {
          id_transfer?: string;
          id_shop?: string;
          transfer_number?: string;
          id_neighbor?: string;
          direction?: string;
          total_items_count?: number | null;
          total_items_value?: number | null;
          gold_grams?: number | null;
          gold_value?: number | null;
          money_amount?: number | null;
          total_value?: number | null;
          status?: string;
          due_date?: string | null;
          return_date?: string | null;
          notes?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          rejected_by?: string | null;
          rejected_at?: string | null;
          rejection_reason?: string | null;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
          version?: number;
        };
        Relationships: [];
      };
      stone_types: {
        Row: {
          category: string;
          created_at: string;
          created_by: string;
          deleted_at: string | null;
          description: string | null;
          id_shop: string;
          id_stone_type: string;
          mohs_hardness: number | null;
          sort_order: number | null;
          stone_name: string;
          updated_at: string;
        };
        Insert: {
          category: string;
          created_at?: string;
          created_by: string;
          deleted_at?: string | null;
          description?: string | null;
          id_shop: string;
          id_stone_type?: string;
          mohs_hardness?: number | null;
          sort_order?: number | null;
          stone_name: string;
          updated_at?: string;
        };
        Update: {
          category?: string;
          created_at?: string;
          created_by?: string;
          deleted_at?: string | null;
          description?: string | null;
          id_shop?: string;
          id_stone_type?: string;
          mohs_hardness?: number | null;
          sort_order?: number | null;
          stone_name?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      supplier_categories: {
        Row: {
          category_name: string;
          created_at: string;
          created_by: string;
          deleted_at: string | null;
          description: string | null;
          id_shop: string;
          id_supplier_category: string;
          sort_order: number | null;
          updated_at: string;
        };
        Insert: {
          category_name: string;
          created_at?: string;
          created_by: string;
          deleted_at?: string | null;
          description?: string | null;
          id_shop: string;
          id_supplier_category?: string;
          sort_order?: number | null;
          updated_at?: string;
        };
        Update: {
          category_name?: string;
          created_at?: string;
          created_by?: string;
          deleted_at?: string | null;
          description?: string | null;
          id_shop?: string;
          id_supplier_category?: string;
          sort_order?: number | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      supplier_payments: {
        Row: {
          amount: number;
          card_amount: number | null;
          cash_amount: number | null;
          cheque_amount: number | null;
          cheque_bank: string | null;
          cheque_cleared_date: string | null;
          cheque_date: string | null;
          cheque_number: string | null;
          cheque_status: string | null;
          created_at: string;
          created_by: string;
          gold_amount: number | null;
          gold_rate_per_gram: number | null;
          gold_weight_grams: number | null;
          id_payment: string;
          id_purchase: string | null;
          id_shop: string;
          id_supplier: string;
          notes: string | null;
          payment_date: string;
          payment_type: string;
          transfer_amount: number | null;
        };
        Insert: {
          amount: number;
          card_amount?: number | null;
          cash_amount?: number | null;
          cheque_amount?: number | null;
          cheque_bank?: string | null;
          cheque_cleared_date?: string | null;
          cheque_date?: string | null;
          cheque_number?: string | null;
          cheque_status?: string | null;
          created_at?: string;
          created_by: string;
          gold_amount?: number | null;
          gold_rate_per_gram?: number | null;
          gold_weight_grams?: number | null;
          id_payment?: string;
          id_purchase?: string | null;
          id_shop: string;
          id_supplier: string;
          notes?: string | null;
          payment_date: string;
          payment_type: string;
          transfer_amount?: number | null;
        };
        Update: {
          amount?: number;
          card_amount?: number | null;
          cash_amount?: number | null;
          cheque_amount?: number | null;
          cheque_bank?: string | null;
          cheque_cleared_date?: string | null;
          cheque_date?: string | null;
          cheque_number?: string | null;
          cheque_status?: string | null;
          created_at?: string;
          created_by?: string;
          gold_amount?: number | null;
          gold_rate_per_gram?: number | null;
          gold_weight_grams?: number | null;
          id_payment?: string;
          id_purchase?: string | null;
          id_shop?: string;
          id_supplier?: string;
          notes?: string | null;
          payment_date?: string;
          payment_type?: string;
          transfer_amount?: number | null;
        };
        Relationships: [];
      };
      supplier_transactions: {
        Row: {
          balance_after: number;
          created_at: string;
          created_by: string;
          credit_amount: number;
          debit_amount: number;
          description: string | null;
          id_shop: string;
          id_supplier: string;
          id_transaction: string;
          reference_id: string | null;
          reference_type: string | null;
          sequence_number: number;
          transaction_type: string;
        };
        Insert: {
          balance_after: number;
          created_at?: string;
          created_by: string;
          credit_amount?: number;
          debit_amount?: number;
          description?: string | null;
          id_shop: string;
          id_supplier: string;
          id_transaction?: string;
          reference_id?: string | null;
          reference_type?: string | null;
          sequence_number?: number;
          transaction_type: string;
        };
        Update: {
          balance_after?: number;
          created_at?: string;
          created_by?: string;
          credit_amount?: number;
          debit_amount?: number;
          description?: string | null;
          id_shop?: string;
          id_supplier?: string;
          id_transaction?: string;
          reference_id?: string | null;
          reference_type?: string | null;
          sequence_number?: number;
          transaction_type?: string;
        };
        Relationships: [];
      };
      suppliers: {
        Row: {
          address: string | null;
          company_name: string;
          contact_person: string | null;
          created_at: string;
          created_by: string;
          current_balance: number;
          deleted_at: string | null;
          email: string | null;
          id_shop: string;
          id_supplier: string;
          id_supplier_category: string | null;
          notes: string | null;
          phone: string | null;
          status: string | null;
          tax_id: string | null;
          updated_at: string;
          updated_by: string | null;
          version: number;
        };
        Insert: {
          address?: string | null;
          company_name: string;
          contact_person?: string | null;
          created_at?: string;
          created_by: string;
          current_balance?: number;
          deleted_at?: string | null;
          email?: string | null;
          id_shop: string;
          id_supplier?: string;
          id_supplier_category?: string | null;
          notes?: string | null;
          phone?: string | null;
          status?: string | null;
          tax_id?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          version?: number;
        };
        Update: {
          address?: string | null;
          company_name?: string;
          contact_person?: string | null;
          created_at?: string;
          created_by?: string;
          current_balance?: number;
          deleted_at?: string | null;
          email?: string | null;
          id_shop?: string;
          id_supplier?: string;
          id_supplier_category?: string | null;
          notes?: string | null;
          phone?: string | null;
          status?: string | null;
          tax_id?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          version?: number;
        };
        Relationships: [];
      };
      users: {
        Row: {
          address: string | null;
          auth_id: string;
          city: string | null;
          country: string | null;
          created_at: string;
          deleted_at: string | null;
          email: string;
          full_name: string;
          id_user: string;
          phone: string | null;
          province: string | null;
          stripe_customer_id: string | null;
          updated_at: string;
        };
        Insert: {
          address?: string | null;
          auth_id: string;
          city?: string | null;
          country?: string | null;
          created_at?: string;
          deleted_at?: string | null;
          email: string;
          full_name: string;
          id_user?: string;
          phone?: string | null;
          province?: string | null;
          stripe_customer_id?: string | null;
          updated_at?: string;
        };
        Update: {
          address?: string | null;
          auth_id?: string;
          city?: string | null;
          country?: string | null;
          created_at?: string;
          deleted_at?: string | null;
          email?: string;
          full_name?: string;
          id_user?: string;
          phone?: string | null;
          province?: string | null;
          stripe_customer_id?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      workshop_orders: {
        Row: {
          actual_cost: number | null;
          completed_date: string | null;
          created_at: string;
          created_by: string;
          deleted_at: string | null;
          delivered_date: string | null;
          description: string | null;
          estimated_completion_date: string | null;
          estimated_cost: number | null;
          id_customer: string | null;
          id_inventory_item: string | null;
          id_shop: string;
          id_workshop: string;
          id_workshop_order: string;
          item_description: string | null;
          item_source: string;
          labor_cost: number | null;
          materials_used: Json | null;
          notes: string | null;
          order_number: string;
          order_type: string;
          paid_amount: number;
          payment_status: string | null;
          received_date: string;
          status: string | null;
          updated_at: string;
          updated_by: string | null;
          version: number;
        };
        Insert: {
          actual_cost?: number | null;
          completed_date?: string | null;
          created_at?: string;
          created_by: string;
          deleted_at?: string | null;
          delivered_date?: string | null;
          description?: string | null;
          estimated_completion_date?: string | null;
          estimated_cost?: number | null;
          id_customer?: string | null;
          id_inventory_item?: string | null;
          id_shop: string;
          id_workshop: string;
          id_workshop_order?: string;
          item_description?: string | null;
          item_source: string;
          labor_cost?: number | null;
          materials_used?: Json | null;
          notes?: string | null;
          order_number: string;
          order_type: string;
          paid_amount?: number;
          payment_status?: string | null;
          received_date: string;
          status?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          version?: number;
        };
        Update: {
          actual_cost?: number | null;
          completed_date?: string | null;
          created_at?: string;
          created_by?: string;
          deleted_at?: string | null;
          delivered_date?: string | null;
          description?: string | null;
          estimated_completion_date?: string | null;
          estimated_cost?: number | null;
          id_customer?: string | null;
          id_inventory_item?: string | null;
          id_shop?: string;
          id_workshop?: string;
          id_workshop_order?: string;
          item_description?: string | null;
          item_source?: string;
          labor_cost?: number | null;
          materials_used?: Json | null;
          notes?: string | null;
          order_number?: string;
          order_type?: string;
          paid_amount?: number;
          payment_status?: string | null;
          received_date?: string;
          status?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          version?: number;
        };
        Relationships: [];
      };
      workshop_payments: {
        Row: {
          amount: number;
          cheque_bank: string | null;
          cheque_cleared_date: string | null;
          cheque_date: string | null;
          cheque_number: string | null;
          cheque_status: string | null;
          created_at: string;
          created_by: string;
          id_payment: string;
          id_shop: string;
          id_workshop: string;
          id_workshop_order: string | null;
          notes: string | null;
          payment_date: string;
          payment_type: string;
        };
        Insert: {
          amount: number;
          cheque_bank?: string | null;
          cheque_cleared_date?: string | null;
          cheque_date?: string | null;
          cheque_number?: string | null;
          cheque_status?: string | null;
          created_at?: string;
          created_by: string;
          id_payment?: string;
          id_shop: string;
          id_workshop: string;
          id_workshop_order?: string | null;
          notes?: string | null;
          payment_date: string;
          payment_type: string;
        };
        Update: {
          amount?: number;
          cheque_bank?: string | null;
          cheque_cleared_date?: string | null;
          cheque_date?: string | null;
          cheque_number?: string | null;
          cheque_status?: string | null;
          created_at?: string;
          created_by?: string;
          id_payment?: string;
          id_shop?: string;
          id_workshop?: string;
          id_workshop_order?: string | null;
          notes?: string | null;
          payment_date?: string;
          payment_type?: string;
        };
        Relationships: [];
      };
      workshop_transactions: {
        Row: {
          balance_after: number;
          created_at: string;
          created_by: string;
          credit_amount: number;
          debit_amount: number;
          description: string | null;
          id_shop: string;
          id_transaction: string;
          id_workshop: string;
          reference_id: string | null;
          reference_type: string | null;
          sequence_number: number;
          transaction_type: string;
        };
        Insert: {
          balance_after: number;
          created_at?: string;
          created_by: string;
          credit_amount?: number;
          debit_amount?: number;
          description?: string | null;
          id_shop: string;
          id_transaction?: string;
          id_workshop: string;
          reference_id?: string | null;
          reference_type?: string | null;
          sequence_number?: number;
          transaction_type: string;
        };
        Update: {
          balance_after?: number;
          created_at?: string;
          created_by?: string;
          credit_amount?: number;
          debit_amount?: number;
          description?: string | null;
          id_shop?: string;
          id_transaction?: string;
          id_workshop?: string;
          reference_id?: string | null;
          reference_type?: string | null;
          sequence_number?: number;
          transaction_type?: string;
        };
        Relationships: [];
      };
      workshops: {
        Row: {
          address: string | null;
          contact_person: string | null;
          created_at: string;
          created_by: string;
          current_balance: number;
          deleted_at: string | null;
          email: string | null;
          hourly_rate: number | null;
          id_shop: string;
          id_workshop: string;
          is_internal: boolean;
          notes: string | null;
          phone: string | null;
          specialization: string | null;
          status: string | null;
          updated_at: string;
          updated_by: string | null;
          version: number;
          workshop_name: string;
        };
        Insert: {
          address?: string | null;
          contact_person?: string | null;
          created_at?: string;
          created_by: string;
          current_balance?: number;
          deleted_at?: string | null;
          email?: string | null;
          hourly_rate?: number | null;
          id_shop: string;
          id_workshop?: string;
          is_internal?: boolean;
          notes?: string | null;
          phone?: string | null;
          specialization?: string | null;
          status?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          version?: number;
          workshop_name: string;
        };
        Update: {
          address?: string | null;
          contact_person?: string | null;
          created_at?: string;
          created_by?: string;
          current_balance?: number;
          deleted_at?: string | null;
          email?: string | null;
          hourly_rate?: number | null;
          id_shop?: string;
          id_workshop?: string;
          is_internal?: boolean;
          notes?: string | null;
          phone?: string | null;
          specialization?: string | null;
          status?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          version?: number;
          workshop_name?: string;
        };
        Relationships: [];
      };
      file_uploads: {
        Row: {
          id_file: string;
          id_shop: string;
          file_name: string;
          file_path: string;
          file_size_bytes: number;
          mime_type: string;
          entity_type: string | null;
          entity_id: string | null;
          uploaded_by: string;
          created_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id_file?: string;
          id_shop: string;
          file_name: string;
          file_path: string;
          file_size_bytes: number;
          mime_type: string;
          entity_type?: string | null;
          entity_id?: string | null;
          uploaded_by: string;
          created_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id_file?: string;
          id_shop?: string;
          file_name?: string;
          file_path?: string;
          file_size_bytes?: number;
          mime_type?: string;
          entity_type?: string | null;
          entity_id?: string | null;
          uploaded_by?: string;
          created_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      item_certifications: {
        Row: {
          id_certification: string;
          id_shop: string;
          id_item: string;
          certification_type: string;
          certificate_number: string;
          issuing_authority: string;
          issue_date: string | null;
          expiry_date: string | null;
          appraised_value: number | null;
          currency: string | null;
          id_file_upload: string | null;
          verification_url: string | null;
          notes: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id_certification?: string;
          id_shop: string;
          id_item: string;
          certification_type: string;
          certificate_number: string;
          issuing_authority: string;
          issue_date?: string | null;
          expiry_date?: string | null;
          appraised_value?: number | null;
          currency?: string | null;
          id_file_upload?: string | null;
          verification_url?: string | null;
          notes?: string | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id_certification?: string;
          id_shop?: string;
          id_item?: string;
          certification_type?: string;
          certificate_number?: string;
          issuing_authority?: string;
          issue_date?: string | null;
          expiry_date?: string | null;
          appraised_value?: number | null;
          currency?: string | null;
          id_file_upload?: string | null;
          verification_url?: string | null;
          notes?: string | null;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      payment_reminders: {
        Row: {
          id_reminder: string;
          id_shop: string;
          id_supplier: string;
          id_purchase: string | null;
          id_payment: string | null;
          reminder_type: string;
          due_date: string;
          amount: number;
          status: string | null;
          reminder_count: number;
          last_reminded_at: string | null;
          next_reminder_date: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id_reminder?: string;
          id_shop: string;
          id_supplier: string;
          id_purchase?: string | null;
          id_payment?: string | null;
          reminder_type: string;
          due_date: string;
          amount: number;
          status?: string | null;
          reminder_count?: number;
          last_reminded_at?: string | null;
          next_reminder_date?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id_reminder?: string;
          id_shop?: string;
          id_supplier?: string;
          id_purchase?: string | null;
          id_payment?: string | null;
          reminder_type?: string;
          due_date?: string;
          amount?: number;
          status?: string | null;
          reminder_count?: number;
          last_reminded_at?: string | null;
          next_reminder_date?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      roles: {
        Row: {
          id_role: string;
          role_name: string;
          description: string | null;
        };
        Insert: {
          id_role?: string;
          role_name: string;
          description?: string | null;
        };
        Update: {
          id_role?: string;
          role_name?: string;
          description?: string | null;
        };
        Relationships: [];
      };
      shop_access: {
        Row: {
          id_access: string;
          id_shop: string;
          id_user: string;
          id_role: string;
          permissions: Json | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id_access?: string;
          id_shop: string;
          id_user: string;
          id_role: string;
          permissions?: Json | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id_access?: string;
          id_shop?: string;
          id_user?: string;
          id_role?: string;
          permissions?: Json | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      staff_invitations: {
        Row: {
          id_invitation: string;
          id_shop: string;
          email: string;
          id_role: string;
          permissions: Json | null;
          invitation_token: string;
          invited_by: string;
          expires_at: string;
          status: string | null;
          accepted_by: string | null;
          accepted_at: string | null;
          created_at: string;
          invitation_token_hash: string | null;
        };
        Insert: {
          id_invitation?: string;
          id_shop: string;
          email: string;
          id_role: string;
          permissions?: Json | null;
          invitation_token?: string;
          invited_by: string;
          expires_at: string;
          status?: string | null;
          accepted_by?: string | null;
          accepted_at?: string | null;
          created_at?: string;
          invitation_token_hash?: string | null;
        };
        Update: {
          id_invitation?: string;
          id_shop?: string;
          email?: string;
          id_role?: string;
          permissions?: Json | null;
          invitation_token?: string;
          invited_by?: string;
          expires_at?: string;
          status?: string | null;
          accepted_by?: string | null;
          accepted_at?: string | null;
          created_at?: string;
          invitation_token_hash?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      get_user_shop_ids: {
        Args: Record<PropertyKey, never>;
        Returns: string[];
      };
      get_user_shop_role: {
        Args: {
          p_shop_id: string;
        };
        Returns: string;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

// Helper types for easier usage
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];

// Alias for common naming convention
export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];

// Commonly used table types
export type Shop = Tables<'shops'>;
export type User = Tables<'users'>;
export type Customer = Tables<'customers'>;
export type CustomerTransaction = Tables<'customer_transactions'>;
export type InventoryItem = Tables<'inventory_items'>;
export type ItemStone = Tables<'item_stones'>;
export type Sale = Tables<'sales'>;
export type SaleItem = Tables<'sale_items'>;
export type SalePayment = Tables<'sale_payments'>;
export type Supplier = Tables<'suppliers'>;
export type SupplierCategory = Tables<'supplier_categories'>;
export type SupplierTransaction = Tables<'supplier_transactions'>;
export type SupplierPayment = Tables<'supplier_payments'>;
export type Purchase = Tables<'purchases'>;
export type Workshop = Tables<'workshops'>;
export type WorkshopOrder = Tables<'workshop_orders'>;
export type WorkshopTransaction = Tables<'workshop_transactions'>;
export type WorkshopPayment = Tables<'workshop_payments'>;
export type CourierCompany = Tables<'courier_companies'>;
export type CourierTransaction = Tables<'courier_transactions'>;
export type CourierPayment = Tables<'courier_payments'>;
export type Delivery = Tables<'deliveries'>;
export type Expense = Tables<'expenses'>;
export type ExpenseCategory = Tables<'expense_categories'>;
export type ExpensePayment = Tables<'expense_payments'>;
export type ExpenseApproval = Tables<'expense_approvals'>;
export type RecurringExpense = Tables<'recurring_expenses'>;
export type BudgetCategory = Tables<'budget_categories'>;
export type BudgetAllocation = Tables<'budget_allocations'>;
export type BudgetTransaction = Tables<'budget_transactions'>;
export type RecycledItem = Tables<'recycled_items'>;
export type ProductCategory = Tables<'product_categories'>;
export type MetalType = Tables<'metal_types'>;
export type MetalPurity = Tables<'metal_purities'>;
export type MetalPrice = Tables<'metal_prices'>;
export type StoneType = Tables<'stone_types'>;
export type ProductSize = Tables<'product_sizes'>;
export type ShopSetting = Tables<'shop_settings'>;
export type FileUpload = Tables<'file_uploads'>;
export type ItemCertification = Tables<'item_certifications'>;
export type PaymentReminder = Tables<'payment_reminders'>;
export type Role = Tables<'roles'>;
export type ShopAccess = Tables<'shop_access'>;
export type StaffInvitation = Tables<'staff_invitations'>;
