/**
 * Schema Exports
 * Centralized exports for all Zod validation schemas
 */

// Customer schemas
export {
  // Enums
  clientTypeEnum,
  financialStatusEnum,
  // Field schemas
  customerNameSchema,
  phonePrimarySchema,
  phoneSecondarySchema,
  customerEmailSchema,
  addressFieldSchema,
  citySchema,
  areaSchema,
  streetSchema,
  postalCodeSchema,
  taxIdSchema,
  creditLimitFieldSchema,
  balanceSchema,
  isVipSchema,
  customerNotesSchema,
  // Main schemas
  customerSchema,
  customerCreateSchema,
  customerUpdateSchema,
  customerQuickAddSchema,
  creditLimitSchema,
  creditLimitUpdateSchema,
  customerSearchSchema,
  // Validation helpers
  validateCustomer,
  validateCustomerQuickAdd,
  validateCreditLimit,
  validateCustomerSearch,
  formatCustomerErrors,
} from './customer';

// Customer types
export type {
  ClientType,
  FinancialStatus,
  CustomerInput,
  CustomerCreateInput,
  CustomerUpdateInput,
  CustomerQuickAddInput,
  CreditLimitInput,
  CreditLimitUpdateInput,
  CustomerSearchInput,
} from './customer';

// Inventory schemas
export {
  // Enums
  itemTypeEnum,
  ownershipTypeEnum,
  sourceTypeEnum,
  inventoryStatusEnum,
  goldColorEnum,
  certificationTypeEnum,
  // Field schemas
  itemNameSchema,
  inventoryBarcodeSchema,
  inventorySkuSchema,
  weightGramsSchema,
  stoneWeightCaratsSchema,
  purchasePriceSchema,
  currencyCodeSchema,
  stoneCountSchema,
  stoneWeightRequiredSchema,
  stonePositionSchema,
  stoneClaritySchema,
  stoneColorSchema,
  stoneCutSchema,
  estimatedValueSchema,
  certificateNumberSchema,
  issuingAuthoritySchema,
  appraisedValueSchema,
  verificationUrlSchema,
  certificationDateSchema,
  // Main schemas
  inventoryItemSchema,
  inventoryItemSimpleSchema,
  inventoryItemUpdateSchema,
  itemStoneSchema,
  itemStoneCreateSchema,
  itemStoneUpdateSchema,
  itemCertificationSchema,
  itemCertificationCreateSchema,
  itemCertificationUpdateSchema,
  inventoryFilterSchema,
  priceRangeSchema,
  weightRangeSchema,
  // Validation helpers
  validateInventoryItem,
  validateItemStone,
  validateItemCertification,
  validateInventoryFilter,
} from './inventory';

// Inventory types
export type {
  ItemType,
  OwnershipType,
  SourceType,
  InventoryStatus,
  GoldColor,
  CertificationType,
  InventoryItemInput,
  InventoryItemSimpleInput,
  InventoryItemUpdateInput,
  ItemStoneInput,
  ItemStoneCreateInput,
  ItemStoneUpdateInput,
  ItemCertificationInput,
  ItemCertificationCreateInput,
  ItemCertificationUpdateInput,
  InventoryFilterInput,
  PriceRangeInput,
  WeightRangeInput,
} from './inventory';

// Sales schemas
export {
  // Enums
  saleStatusEnum,
  paymentStatusEnum,
  paymentTypeEnum,
  discountTypeEnum,
  chequeStatusEnum,
  saleItemStatusEnum,
  // Field schemas
  saleNumberSchema,
  saleDateSchema,
  amountSchema,
  positiveAmountSchema,
  unitPriceSchema,
  quantitySchema,
  discountPercentSchema,
  discountValueSchema,
  saleItemNameSchema,
  saleWeightGramsSchema,
  saleItemBarcodeSchema,
  metalTypeNameSchema,
  metalPurityNameSchema,
  returnReasonSchema,
  paymentDateSchema,
  cardLastFourSchema,
  authorizationCodeSchema,
  bankNameSchema,
  transactionReferenceSchema,
  chequeNumberSchema,
  chequeDateSchema,
  // Main schemas
  saleSchema,
  saleCreateSchema,
  saleUpdateSchema,
  saleCompleteSchema,
  saleVoidSchema,
  saleItemSchema,
  saleItemCreateSchema,
  saleItemUpdateSchema,
  saleItemReturnSchema,
  salePaymentSchema,
  salePaymentSimpleSchema,
  discountSchema,
  optionalDiscountSchema,
  saleFilterSchema,
  saleDateRangeSchema,
  amountRangeSchema,
  // Validation helpers
  validateSale,
  validateSaleItem,
  validateSalePayment,
  validateDiscount,
  validateSaleFilter,
  formatSaleErrors,
  calculateDiscountAmount,
  determinePaymentStatus,
} from './sales';

// Sales types
export type {
  SaleStatus,
  PaymentStatus as SalePaymentStatus,
  PaymentType,
  DiscountType,
  ChequeStatus,
  SaleItemStatus,
  SaleInput,
  SaleCreateInput,
  SaleUpdateInput,
  SaleCompleteInput,
  SaleVoidInput,
  SaleItemInput,
  SaleItemCreateInput,
  SaleItemUpdateInput,
  SaleItemReturnInput,
  SalePaymentInput,
  SalePaymentSimpleInput,
  DiscountInput,
  OptionalDiscountInput,
  SaleFilterInput,
  SaleDateRangeInput,
  AmountRangeInput,
} from './sales';

// Supplier schemas
export {
  // Enums
  supplierTransactionTypeEnum,
  supplierReferenceTypeEnum,
  // Field schemas
  companyNameSchema,
  contactNameSchema,
  supplierPhoneSchema,
  supplierEmailSchema,
  addressLineSchema,
  supplierCitySchema,
  stateSchema,
  supplierPostalCodeSchema,
  countrySchema,
  supplierTaxIdSchema,
  bankNameSchema as supplierBankNameSchema,
  bankAccountSchema,
  bankIbanSchema,
  bankSwiftSchema,
  supplierCreditLimitSchema,
  paymentTermsDaysSchema,
  supplierNotesSchema,
  paymentAmountSchema,
  // Main schemas
  supplierSchema,
  supplierCreateSchema,
  supplierUpdateSchema,
  supplierCategorySchema,
  supplierCategoryCreateSchema,
  supplierCategoryUpdateSchema,
  supplierPaymentSchema,
  supplierPaymentWithReferenceSchema,
  supplierSearchSchema,
  supplierQuickAddSchema,
  // Validation helpers
  validateSupplier,
  validateSupplierQuickAdd,
  validateSupplierCategory,
  validateSupplierPayment,
  validateSupplierSearch,
  formatSupplierErrors,
} from './supplier';

// Supplier types
export type {
  SupplierTransactionType,
  SupplierReferenceType,
  SupplierInput,
  SupplierCreateInput,
  SupplierUpdateInput,
  SupplierQuickAddInput,
  SupplierCategoryInput,
  SupplierCategoryCreateInput,
  SupplierCategoryUpdateInput,
  SupplierPaymentInput,
  SupplierPaymentWithReferenceInput,
  SupplierSearchInput,
} from './supplier';

// Purchase schemas
export {
  // Enums
  purchasePaymentStatusEnum,
  // Field schemas
  purchaseNumberSchema,
  invoiceNumberSchema,
  purchaseDateSchema,
  totalItemsSchema,
  totalWeightGramsSchema,
  purchaseAmountSchema,
  positiveAmountSchema as purchasePositiveAmountSchema,
  // Main schemas
  purchaseSchema,
  purchaseCreateSchema,
  purchaseUpdateSchema,
  recordPurchasePaymentSchema,
  purchaseFilterSchema,
  purchaseDateRangeSchema,
  purchaseAmountRangeSchema,
  // Validation helpers
  validatePurchase,
  validatePurchaseUpdate,
  validatePurchaseFilter,
  formatPurchaseErrors,
  determinePurchasePaymentStatus,
} from './purchase';

// Purchase types
export type {
  PurchasePaymentStatus,
  PurchaseInput,
  PurchaseCreateInput,
  PurchaseUpdateInput,
  RecordPurchasePaymentInput,
  PurchaseFilterInput,
  PurchaseDateRangeInput,
  PurchaseAmountRangeInput,
} from './purchase';

// Budget schemas
export {
  // Enums
  budgetTypeEnum,
  budgetFrequencyEnum,
  budgetAllocationStatusEnum,
  budgetTransactionTypeEnum,
  budgetApprovalStatusEnum,
  // Field schemas
  budgetCategoryNameSchema,
  budgetDescriptionSchema,
  defaultAmountSchema,
  approvalThresholdSchema,
  sortOrderSchema,
  allocatedAmountSchema,
  usedAmountSchema,
  rolloverAmountSchema,
  budgetNotesSchema,
  transactionAmountSchema,
  transactionDescriptionSchema,
  // Main schemas
  budgetCategorySchema,
  budgetCategoryCreateSchema,
  budgetCategoryUpdateSchema,
  budgetAllocationSchema,
  budgetAllocationCreateSchema,
  budgetAllocationUpdateSchema,
  budgetAdjustmentSchema,
  budgetTransferSchema,
  budgetTransactionSchema,
  budgetTransactionCreateSchema,
  budgetCategorySearchSchema,
  budgetAllocationSearchSchema,
  budgetVsActualQuerySchema,
  budgetPeriodSchema,
  monthlyPeriodSchema,
  // Validation helpers
  validateBudgetCategory,
  validateBudgetAllocation,
  validateBudgetAdjustment,
  validateBudgetTransfer,
  validateBudgetTransaction,
  validateBudgetPeriod,
  formatBudgetErrors,
  calculateRemainingBudget,
  isOverBudget,
  calculateBudgetUtilization,
} from './budget';

// Budget types
export type {
  BudgetType,
  BudgetFrequency,
  BudgetAllocationStatus,
  BudgetTransactionType,
  BudgetApprovalStatus,
  BudgetCategoryInput,
  BudgetCategoryCreateInput,
  BudgetCategoryUpdateInput,
  BudgetAllocationInput,
  BudgetAllocationCreateInput,
  BudgetAllocationUpdateInput,
  BudgetAdjustmentInput,
  BudgetTransferInput,
  BudgetTransactionInput,
  BudgetTransactionCreateInput,
  BudgetCategorySearchInput,
  BudgetAllocationSearchInput,
  BudgetVsActualQueryInput,
  BudgetPeriodInput,
} from './budget';

// Delivery schemas
export {
  // Enums
  deliveryStatusEnum,
  costPaidByEnum,
  courierStatusEnum,
  courierTransactionTypeEnum,
  courierReferenceTypeEnum,
  // Field schemas
  deliveryAddressSchema,
  optionalDeliveryAddressSchema,
  trackingNumberSchema,
  deliveryCostSchema,
  recipientNameSchema,
  deliveryNotesSchema,
  shippedDateSchema,
  estimatedDeliveryDateSchema,
  deliveredDateSchema,
  courierCompanyNameSchema,
  courierContactPersonSchema,
  courierPhoneSchema,
  courierEmailSchema,
  courierWebsiteSchema,
  courierNotesSchema,
  courierPaymentAmountSchema,
  // Main schemas
  deliverySchema,
  deliveryCreateSchema,
  deliveryUpdateSchema,
  deliveryStatusUpdateSchema,
  courierSchema,
  courierCreateSchema,
  courierUpdateSchema,
  courierPaymentSchema,
  courierPaymentWithReferenceSchema,
  deliverySearchSchema,
  courierSearchSchema,
  // Validation helpers
  validateDelivery,
  validateDeliveryStatusUpdate,
  validateCourier,
  validateCourierPayment,
  validateDeliverySearch,
  validateCourierSearch,
  formatDeliveryErrors,
  isDeliveryEditable,
  getAllowedStatusTransitions,
} from './delivery';

// Delivery types
export type {
  DeliveryStatus,
  CostPaidBy,
  CourierStatus,
  CourierTransactionType,
  CourierReferenceType,
  DeliveryInput,
  DeliveryCreateInput,
  DeliveryUpdateInput,
  DeliveryStatusUpdateInput,
  CourierInput,
  CourierCreateInput,
  CourierUpdateInput,
  CourierPaymentInput,
  CourierPaymentWithReferenceInput,
  DeliverySearchInput,
  CourierSearchInput,
} from './delivery';

// Payment Reminder schemas
export {
  // Enums
  reminderTypeEnum,
  reminderStatusEnum,
  entityTypeEnum,
  // Field schemas
  reminderAmountSchema,
  dueDateSchema,
  nextReminderDateSchema,
  reminderNotesSchema,
  reminderCountSchema,
  snoozeDaysSchema,
  // Main schemas
  paymentReminderSchema,
  paymentReminderCreateSchema,
  paymentReminderUpdateSchema,
  paymentReminderQuickAddSchema,
  markReminderCompleteSchema,
  snoozeReminderSchema,
  // Search/filter schemas
  paymentReminderSearchSchema,
  upcomingRemindersSchema,
  overdueRemindersSchema,
  // Validation helpers
  validatePaymentReminder,
  validatePaymentReminderQuickAdd,
  validateMarkComplete,
  validateSnooze,
  validatePaymentReminderSearch,
  formatPaymentReminderErrors,
  // Utility functions
  isReminderOverdue,
  isReminderUpcoming,
  calculateSnoozedDueDate,
  getDaysUntilDue,
} from './paymentReminder';

// Payment Reminder types
export type {
  ReminderType,
  ReminderStatus,
  EntityType,
  PaymentReminderInput,
  PaymentReminderCreateInput,
  PaymentReminderUpdateInput,
  PaymentReminderQuickAddInput,
  MarkReminderCompleteInput,
  SnoozeReminderInput,
  PaymentReminderSearchInput,
  UpcomingRemindersInput,
  OverdueRemindersInput,
} from './paymentReminder';

// Workshop schemas
export {
  // Enums
  workshopOrderTypeEnum,
  workshopOrderStatusEnum,
  workshopTransactionTypeEnum,
  workshopReferenceTypeEnum,
  workshopStatusEnum,
  itemSourceEnum,
  paymentStatusEnum as workshopPaymentStatusEnum,
  // Field schemas
  workshopNameSchema,
  workshopContactPersonSchema,
  workshopPhoneSchema,
  workshopEmailSchema,
  workshopSpecializationSchema,
  workshopAddressSchema,
  workshopNotesSchema,
  orderNumberSchema,
  orderDescriptionSchema,
  orderItemDescriptionSchema,
  itemDescriptionSchema,
  estimatedCostSchema,
  actualCostSchema,
  laborCostSchema,
  materialsUsedSchema,
  workshopPaymentAmountSchema,
  // Main schemas
  workshopSchema,
  workshopCreateSchema,
  workshopUpdateSchema,
  workshopOrderSchema,
  workshopOrderCreateSchema,
  workshopOrderUpdateSchema,
  workshopOrderStatusUpdateSchema,
  workshopOrderItemSchema,
  workshopOrderItemCreateSchema,
  workshopOrderItemUpdateSchema,
  workshopPaymentSchema,
  workshopPaymentWithReferenceSchema,
  workshopSearchSchema,
  workshopOrderSearchSchema,
  workshopQuickAddSchema,
  // Validation helpers
  validateWorkshop,
  validateWorkshopQuickAdd,
  validateWorkshopOrder,
  validateWorkshopPayment,
  validateWorkshopSearch,
  validateWorkshopOrderSearch,
  formatWorkshopErrors,
  // Utility functions
  generateOrderNumberFormat,
  parseOrderNumber,
} from './workshop';

// Workshop types
export type {
  WorkshopOrderType,
  WorkshopOrderStatus,
  WorkshopTransactionType,
  WorkshopReferenceType,
  WorkshopStatus,
  ItemSource,
  PaymentStatus as WorkshopPaymentStatus,
  WorkshopInput,
  WorkshopCreateInput,
  WorkshopUpdateInput,
  WorkshopQuickAddInput,
  WorkshopOrderInput,
  WorkshopOrderCreateInput,
  WorkshopOrderUpdateInput,
  WorkshopOrderStatusUpdateInput,
  WorkshopOrderItemInput,
  WorkshopOrderItemCreateInput,
  WorkshopOrderItemUpdateInput,
  WorkshopPaymentInput,
  WorkshopPaymentWithReferenceInput,
  WorkshopSearchInput,
  WorkshopOrderSearchInput,
} from './workshop';

// Expense schemas
export {
  // Enums
  expensePaymentStatusEnum,
  expenseApprovalStatusEnum,
  expenseCategoryTypeEnum,
  expenseFrequencyEnum,
  recurringExpenseStatusEnum,
  expensePaymentTypeEnum,
  expenseChequeStatusEnum,
  // Field schemas
  expenseNumberSchema,
  expenseDescriptionSchema,
  vendorNameSchema,
  expenseAmountSchema,
  paidAmountSchema,
  expenseDateSchema,
  dueDateSchema as expenseDueDateSchema,
  expenseNotesSchema,
  rejectionReasonSchema,
  expenseCategoryNameSchema,
  categoryDescriptionSchema,
  sortOrderSchema as expenseSortOrderSchema,
  dayOfMonthSchema,
  dayOfWeekSchema,
  paymentAmountSchema as expensePaymentAmountSchema,
  chequeNumberSchema as expenseChequeNumberSchema,
  chequeBankSchema,
  // Main schemas
  expenseSchema,
  expenseCreateSchema,
  expenseUpdateSchema,
  expenseApprovalSchema,
  expenseRejectionSchema,
  expenseCategorySchema,
  expenseCategoryCreateSchema,
  expenseCategoryUpdateSchema,
  recurringExpenseSchema,
  recurringExpenseCreateSchema,
  recurringExpenseUpdateSchema,
  recurringExpenseStatusChangeSchema,
  expensePaymentSchema,
  expenseSearchSchema,
  recurringExpenseSearchSchema,
  expenseQuickAddSchema,
  // Validation helpers
  validateExpense,
  validateExpenseQuickAdd,
  validateExpenseCategory,
  validateRecurringExpense,
  validateExpensePayment,
  validateExpenseSearch,
  formatExpenseErrors,
  determineExpensePaymentStatus,
  calculateNextDueDate,
} from './expense';

// Expense types
export type {
  ExpensePaymentStatus,
  ExpenseApprovalStatus,
  ExpenseCategoryType,
  ExpenseFrequency,
  RecurringExpenseStatus,
  ExpensePaymentType,
  ExpenseChequeStatus,
  ExpenseInput,
  ExpenseCreateInput,
  ExpenseUpdateInput,
  ExpenseQuickAddInput,
  ExpenseApprovalInput,
  ExpenseRejectionInput,
  ExpenseCategoryInput,
  ExpenseCategoryCreateInput,
  ExpenseCategoryUpdateInput,
  RecurringExpenseInput,
  RecurringExpenseCreateInput,
  RecurringExpenseUpdateInput,
  RecurringExpenseStatusChangeInput,
  ExpensePaymentInput,
  ExpenseSearchInput,
  RecurringExpenseSearchInput,
} from './expense';

// Common schema utilities (edge case handling)
export {
  // String utilities
  normalizeWhitespace,
  emptyToNull,
  emptyToUndefined,
  // Unicode patterns
  JEWELRY_SYMBOLS_PATTERN,
  UNICODE_NAME_PATTERN,
  // Unicode-aware schemas
  createUnicodeNameSchema,
  createArabicNameSchema,
  createProductDescriptionSchema,
  // Precision number schemas
  monetaryAmountSchema,
  signedMonetaryAmountSchema,
  weightGramsSchema as preciseWeightGramsSchema,
  weightCaratsSchema,
  percentageSchema,
  quantitySchema as preciseQuantitySchema,
  versionSchema,
  // Optional field schemas
  createOptionalStringSchema,
  optionalEmailSchema,
  optionalPhoneSchema,
  // Validation helpers
  isNonEmptyString,
  isPositiveNumber,
  isNonNegativeNumber,
  parseMonetaryValue,
  formatZodErrors,
  safeValidate,
} from './common';
